### ISSUE TITLE
Timeline: Zoom values change by resizing inspector-box/ annotation types-overview

### ISSUE THREAD

**Issue by JStratil** [oaubert/advene#26]
By Resizing the inspector-box (right to the timeline) to the left the visible part of the timeline shrinks and the zoom values drop without changing the size of the annotations. The same is true for the box on the left side of the timeline. In some projects 100%-view (complete overview of the annotations of the projects without horizontally scrolling) is only possible when hiding inspector-box and annotation types-overview. Otherwise the zoom value is locked to a lower percentage. Pressing the + or - buttons or entering a numeric value doesn't help to reach 100%.

**Comment by oaubert** [comment]
The fact that resizing the inspector box changes the zoom level value instead of trying to keep it constant is in fact a feature: since trying to keep the zoom level constant would imply a full redraw of the timeline with every move, which may be slow if there are a large number of annotations, I chose to update the zoom value instead (which is immediate).
The fact that sometimes the 100% zoom level could not be obtained has been fixed in ac3552ffa85d21238e331a929f27d0bf8cc7b099
