### ISSUE TITLE
Package 'advene' has no installation candidate using apt

### ISSUE THREAD

**Issue by nise** [oaubert/advene#64]
Unfortunately the apt installation instruction doesn't work for Ubuntu 20.04. It says there is no installation candidate with the name 'advene advene-full'.

Instead it could be mentioned how to install Advene using dpkg form https://advene.org/download/debian/binary/, e.g.

```
wget https://advene.org/download/debian/binary/advene_3.11.12-1_all.deb
sudo dpkg -i advene_3.11.12-1_all.deb 
```

**Comment by oaubert** [comment]
Hi. Thanks for reporting the issue. It was due to a bad (outdated) ssl configuration on the advene website (not visible in the browser, but when accessing from wget/curl), which caused the download of the advene.list file to silently fail (since --quiet was specified) and create an empty advene.list configuration. I have fixed the server-side issue and tested it on a Ubuntu20. You can reload the file using
`sudo wget --quiet -O /etc/apt/sources.list.d/advene.list https://advene.org/download/debian/binary/advene.list `
and apt update again.

**Comment by nise** [comment]
When executing the suggested command:
`sudo wget --quiet -O /etc/apt/sources.list.d/advene.list https://advene.org/download/debian/binary/advene.list` the follwoing error appears after running `apt-get udate`

```
Err:7 https://advene.org/download/debian/binary  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D489FCE5E532BB23
Reading package lists... Done       
W: GPG error: https://advene.org/download/debian/binary  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D489FCE5E532BB23
E: The repository 'https://advene.org/download/debian/binary  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by oaubert** [comment]
Did you install the repo key with the command `wget --quiet -O - https://olivieraubert.net/olivieraubert.asc | sudo apt-key add - ` ?

**Comment by nise** [comment]
I did not, since it was not mentioned. Now everything works fine!
Thank you for your quick response!

**Comment by oaubert** [comment]
We may not be talking about the same installation instructions then. I am considering https://advene.org/download.html#linux as the reference instructions. Did you get instructions from some other place?
