### ISSUE TITLE
TracePreview and goocanvas

### ISSUE THREAD

**Issue by staphon7** [oaubert/advene#71]
Hello there,  
First, let me thank you for coding Advene.

My operating system is Arch Linux.

Here is the output of `advene --version`:  
Advene v. 3.12 release 20210416

I'm just trying to install Advene the best I can.

Launching Advene from a terminal, the following messages -among some others- are displayed:
```
advene.core.controller INFO Registering Trace view
advene.gui.main INFO Cannot register TracePreview: the goocanvas python module does not seem to be available.
advene.core.controller INFO Registering Trace preview
```

In Arch Linux, the packages about goocanvas are:
- goocanvas -Installed-
- goocanvasmm
- perl-goocanvas2

The python related files that the goocanvas packages installs are:
- /usr/lib/python3.9/site-packages/gi/overrides/GooCanvas.py
- /usr/lib/python3.9/site-packages/gi/overrides/__pycache__/GooCanvas.cpython-39.opt-1.pyc
- /usr/lib/python3.9/site-packages/gi/overrides/__pycache__/GooCanvas.cpython-39.pyc

But there is no specific python package for goocanvas.

I also noticed that when I ask to see the activity trace view, nothing
happens but an error message -I don't put it there, ask me if you want to-.
I think this is related, but I'm not sure.

So I was wondering if I had to search the web and install more packages
-pygoocanvas for example [which is unmaintained, but can be found]-, or
just didn't have to be worried about these messages?

Thank you.

**Comment by oaubert** [comment]
Hi. The goocanvas module was just used by an obsolete plugin. It was not required anyway, and I just removed the culprit and purged Advene of all goocanvas references. It will thus be fixed in the next release, which I plan to do in the coming days/weeks. If you are interested in packaging Advene for arch, do not hesitate to signal any issues. You can get inspiration from the Debian packaging files: https://salsa.debian.org/multimedia-team/advene/-/blob/master/debian/control
