### ISSUE TITLE
Timeline (online) doesn't load

### ISSUE THREAD

**Issue by AdaTsche** [oaubert/advene#92]
Generating the timeline from an azp only displays a blank browser window with the following TypeError

![grafik](https://user-images.githubusercontent.com/25324521/180396999-6bbc6843-c7ad-4936-87e4-93ad123472b0.png)

Offline timeline can be still generated with the before mentioned errors in the issue section.

Tested on Ubuntu with Firefox and Chromium

**Comment by oaubert** [comment]
The online version relies on different versions of the underlying libraries, and these versions were initially specified in the HTML template. This has been fixed in the template file of the AdA project in jan. 2021. I guess you are using an older template. You should merge the `Timeline` view from the `template_ontology.azp`  file. Please test and close this issue if it is ok (or provide more details if not).

**Comment by AdaTsche** [comment]
You're right! somehow I downgraded a file to an holder version. Sorry for the nuissance and thanks for the quick help.
