### ISSUE TITLE
Annotation Splitting Bug

### ISSUE THREAD

**Issue by UnnamedDisaster** [oaubert/advene#94]
When splitting an annotation either by pressing Ctrl. + Enter or by right clicking and using the context menu, the newly split annotation seems to be of a random lenght and not as you would think simply the given annotation split into two. I even had the situatution, that my chosen annotation would split into a new annotation that was so long, that it would overlay the next annotation in the lane.

**Comment by oaubert** [comment]
This is very strange: the code (in core/controller/split_annotation) does not do anything fancy: it checks that the split position is in the annotation boundary. If so, it creates a new annotation starting at the split position and with the same end position as the original annotation, and shortens the original annotation accordingly. Would you have a more precise and reproducible scenario?

**Comment by UnnamedDisaster** [comment]
I do have a video but for the sake of data I will add two stills. Those show an annotation right before and after I use Ctrl. + Enter and nothing else.
![Split Bug 1](https://github.com/oaubert/advene/assets/159791661/5eaddb69-2845-4b80-9773-a253d5c29c38)
![Split Bug 2](https://github.com/oaubert/advene/assets/159791661/1b61ff05-9c96-4179-b077-3bef90d42a2e)

**Comment by oaubert** [comment]
Indeed. I see the bug now, I was not looking at the right part of code. The problem is that the Control-Enter shortcut is used to create a new annotation in the timeline. Normally, splitting is with Control-Shift-Return. But the handler for Control-Enter catches it before (forgot to check if Shift is pressed or not), so it creates a new annotation at the current position instead of splitting the annotation.
I will fix this, but it is a bit confusing anyway - maybe I should switch to another shortcut for splitting, like Control-p. What do you think?

**Comment by UnnamedDisaster** [comment]
I'm sorry Olivier, your mails went under my radar. I'm happy you found the
issue now. If Ctrl. + Enter is in fact used for creating a wholly new
annotation it seems that this was more of a user issue than a bug. But I do
think it would be a good idea to put splitting and New Annotation on two
different key binds. However I think a shortcut that can be used with only
the left hand while using the mouse with the other would be a beneficial
one. Maybe Ctrl + T? The T could be a good visual reminder of a cut due to
the straight vertical line. Or Ctrl + N for New Annotation? I'm not savvy
with all shortcuts so excuse me if there are already shortcuts with those
keys.

And excuse me again for not replying earlier.

Kind regards,
Kevin Huthmann
--------------------------------
***@***.***
